### ISSUE TITLE
Master Todo

### ISSUE THREAD

**Issue by holychowders** [holychowders/inventory_management_system#18]
# Master Todo

## Miscellaneous

- [ ] Items left over from #7 
- [ ] Switch to SQLAlchemy?

## Security

- [ ] Review [S608 hardcoded-sql-expression](https://beta.ruff.rs/docs/rules/hardcoded-sql-expression/) (`ruff`) warnings currently `noqa`'d
  - See [Sql Injection Explained by Example with Express and PostgreSQL](https://youtu.be/Azo9tDUtC9s) (Hussein Nasser)
  - You can use `grep -i S608 ims/*` to find all instances of `S608` being ignored in `ims/`
- [ ] Resolve [S105 hardcoded-password-string](https://beta.ruff.rs/docs/rules/#flake8-bandit-s) (`ruff`) currently `noqa`'d, probably by using environment variables
  - https://github.com/holychowders/inventory_management_system/blob/ca9f779947d949cd4530aeb1f0508de6a315e9c3/ims/__init__.py#L21

## Testing and Verification

- [ ] Test API endpoints (assigned @holychowders) **IN PROGRESS**
  - #25 
  - #28 
- [ ] Test database initialization
- [ ] Make `ims/db.py/ensure_db()` actually check database state even if database file exists rather than just init if it doesn't exist
  - https://github.com/holychowders/inventory_management_system/blob/ca9f779947d949cd4530aeb1f0508de6a315e9c3/ims/db.py#L104

## User Authentication

- [ ] **Fix login page crashes on missing and invalid input (backend validation)**
- [ ] Disallow submitting via "Log In" button with invalid login page inputs (HTML/client-side constraint validation)
- [ ] Add method of disabling user authentication requirements while debugging
- [ ] Hashing passwords in login_credentials table
- [ ] Add user profile creation page (@alycia-sloan ) **IN PROGRESS**

## Completed

- [x] Add a couple of representative screenshots to readme
- [x] Add launch instructions to readme
- [x] Add development setup instructions to readme
- [X] Discuss adding commit linting which follows minimal [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec
  - Added in https://github.com/holychowders/inventory_management_system/commit/e972bddb846a16b8c92aae811fbf0073ff771418
- [X] Fix inconsistent border width of `<textarea>` input fields and other `<input>` fields on product pages
  - https://github.com/holychowders/inventory_management_system/commit/d9af0f56da8d643d65cd5855128e89ab8aa6b811
