### ISSUE TITLE
MVP TODO (DUE 2023-05-12)

### ISSUE THREAD

**Issue by holychowders** [holychowders/inventory_management_system#7]
# MVP TODO (DUE 2023-05-12)

## High Priority
- [ ] Add remaining pages required by the dashboard (Assigned: @holychowders)
  - [X] Customers: #23 
  - [ ] Purchases
  - [ ] Suppliers
- [ ] Add the join table(s) and adjust table creation, sample data population, and queries based on the new tables (Assigned: @alycia-sloan)
  - [X] #19 
  - [ ] `purchase` changes?
- [X] User authentication (Assigned: @alycia-sloan)
  - #24 
  - Implement user authentication (login and logout). The simplest way to do this is probably just going to be checking IDs and PINs against authorized users in the database when the login button is pressed, though we're going to have to also figure out how to make sure that other pages can't be accessed through other means without being logged in. Other means would include clicking on the IMS header on the login page and just navigating directly to a page through the URL bar off the top of my head.
  - The very first part (checking the db) should be relatively trivial, but I have no idea about everything else. I feel like we might need to pull in a 3rd-party auth package. This should be discussed before a solution is implemented.

## ~~Low-Medium Priority~~ (Not Happening)
- [ ] Implement "Search" feature on products page
- [ ] Allow sorting by clicking on table headers on product page
- [ ] Advanced views (requires discussion)
- [ ] Look into using icons in certain places

## Finished

- [x] Implement "Add" feature on products page (Assigned: @holychowders)
  - #20 
- [X] Implement "Submit" button on product edit page (Assigned: @holychowders)
  - #17
- [x] Clean up CSS before adding more pages (Assigned: @holychowders)
- [X] Use the Google Fonts API or whatever to use a font looks nicer than the default one (Assigned: @alycia-sloan)
- [X] The todo in #6
